const regularProducts = [
  { id: "gulf-orchid-naseem", name: "Gulf Orchid Naseem", brand: "Gulf Orchid", sizes: [{ml:3,price:150},{ml:5,price:220},{ml:10,price:380},{ml:15,price:560},{ml:30,price:1090}], tags: [], inStock: true },
  { id: "rayhaan-aquatica", name: "Rayhaan Aquatica", brand: "Rayhaan", sizes: [{ml:3,price:150},{ml:5,price:220},{ml:10,price:380},{ml:15,price:560},{ml:30,price:1090}], tags: [], inStock: false },
  { id: "rayhaan-lion", name: "Rayhaan Lion", brand: "Rayhaan", sizes: [{ml:3,price:150},{ml:5,price:220},{ml:10,price:380},{ml:15,price:560},{ml:30,price:1090}], tags: [], inStock: true },
  { id: "rayhaan-terra", name: "Rayhaan Terra", brand: "Rayhaan", sizes: [{ml:3,price:150},{ml:5,price:220},{ml:10,price:380},{ml:15,price:560},{ml:30,price:1090}], tags: ["new"], inStock: true },
  { id: "davidoff-cool-water", name: "Davidoff Cool Water", brand: "Davidoff", sizes: [{ml:3,price:150},{ml:5,price:220},{ml:10,price:400},{ml:15,price:600},{ml:30,price:1190}], tags: [], inStock: true },
  { id: "riiffs-fareed", name: "Riiffs Fareed", brand: "Riiffs", sizes: [{ml:3,price:160},{ml:5,price:230},{ml:10,price:420},{ml:15,price:610},{ml:30,price:1190}], tags: [], inStock: true },
  { id: "nautica-voyage", name: "Nautica Voyage", brand: "Nautica", sizes: [{ml:3,price:160},{ml:5,price:230},{ml:10,price:420},{ml:15,price:610},{ml:30,price:1190}], tags: [], inStock: true },
  { id: "lattafa-angham", name: "Lattafa Angham", brand: "Lattafa", sizes: [{ml:3,price:160},{ml:5,price:260},{ml:10,price:460},{ml:15,price:680},{ml:30,price:1330}], tags: [], inStock: true },
  { id: "lattafa-khamrah-qahwa", name: "Lattafa Khamrah Qahwa", brand: "Lattafa", sizes: [{ml:3,price:160},{ml:5,price:260},{ml:10,price:460},{ml:15,price:680},{ml:30,price:1330}], tags: [], inStock: true },
  { id: "armaf-cdni-edp", name: "Armaf Club de Nuit Intense Man EDP", brand: "Armaf", sizes: [{ml:3,price:170},{ml:5,price:270},{ml:10,price:490},{ml:15,price:730},{ml:30,price:1450}], tags: [], inStock: true },
  { id: "davidoff-indigo", name: "Davidoff Indigo", brand: "Davidoff", sizes: [{ml:3,price:170},{ml:5,price:270},{ml:10,price:490},{ml:15,price:730},{ml:30,price:1450}], tags: [], inStock: true },
  { id: "lattafa-maahir-legacy", name: "Lattafa Maahir Legacy", brand: "Lattafa", sizes: [{ml:3,price:170},{ml:5,price:270},{ml:10,price:490},{ml:15,price:730},{ml:30,price:1450}], tags: [], inStock: true },
  { id: "rasasi-shuhrah-elixir", name: "Rasasi Shuhrah Elixir", brand: "Rasasi", sizes: [{ml:3,price:170},{ml:5,price:270},{ml:10,price:490},{ml:15,price:730},{ml:30,price:1450}], tags: [], inStock: true },
  { id: "rasasi-hawas", name: "Rasasi Hawas", brand: "Rasasi", sizes: [{ml:3,price:170},{ml:5,price:270},{ml:10,price:490},{ml:15,price:730},{ml:30,price:1450}], tags: [], inStock: true },
  { id: "rasasi-hawas-black", name: "Rasasi Hawas Black", brand: "Rasasi", sizes: [{ml:3,price:170},{ml:5,price:270},{ml:10,price:490},{ml:15,price:730},{ml:30,price:1450}], tags: [], inStock: true },
  { id: "rasasi-hawas-elixir", name: "Rasasi Hawas Elixir", brand: "Rasasi", sizes: [{ml:3,price:170},{ml:5,price:270},{ml:10,price:490},{ml:15,price:730},{ml:30,price:1450}], tags: [], inStock: true },
  { id: "rasasi-hawas-ice", name: "Rasasi Hawas Ice", brand: "Rasasi", sizes: [{ml:3,price:170},{ml:5,price:270},{ml:10,price:490},{ml:15,price:730},{ml:30,price:1450}], tags: [], inStock: true },
  { id: "afnan-modest-une", name: "Afnan Modest Une", brand: "Afnan", sizes: [{ml:3,price:180},{ml:5,price:280},{ml:10,price:500},{ml:15,price:750},{ml:30,price:1470}], tags: [], inStock: true },
  { id: "afnan-9pm", name: "Afnan 9PM", brand: "Afnan", sizes: [{ml:3,price:180},{ml:5,price:290},{ml:10,price:520},{ml:15,price:770},{ml:30,price:1490}], tags: [], inStock: true },
  { id: "lattafa-teriaq-intense", name: "Lattafa Teriaq Intense", brand: "Lattafa", sizes: [{ml:3,price:190},{ml:5,price:320},{ml:10,price:550},{ml:15,price:810}], tags: [], inStock: true },
  { id: "lattafa-dynasty", name: "Lattafa Dynasty", brand: "Lattafa", sizes: [{ml:3,price:190},{ml:5,price:320},{ml:10,price:550},{ml:15,price:810}], tags: [], inStock: true },
  { id: "rasasi-hawas-kobra", name: "Rasasi Hawas Kobra", brand: "Rasasi", sizes: [{ml:3,price:190},{ml:5,price:320},{ml:10,price:550},{ml:15,price:810}], tags: [], inStock: true },
  { id: "rasasi-hawas-malibu", name: "Rasasi Hawas Malibu", brand: "Rasasi", sizes: [{ml:3,price:190},{ml:5,price:320},{ml:10,price:550},{ml:15,price:810}], tags: [], inStock: true },
  { id: "rasasi-hawas-tropical", name: "Rasasi Hawas Tropical", brand: "Rasasi", sizes: [{ml:3,price:190},{ml:5,price:320},{ml:10,price:550},{ml:15,price:810}], tags: [], inStock: true },
  { id: "armaf-cdni-milestone", name: "Armaf Club de Nuit Milestone", brand: "Armaf", sizes: [{ml:3,price:190},{ml:5,price:320},{ml:10,price:550},{ml:15,price:810},{ml:30,price:1570}], tags: [], inStock: true },
  { id: "bentley-silverlake", name: "Bentley Silverlake", brand: "Bentley", sizes: [{ml:3,price:200},{ml:5,price:330},{ml:10,price:590},{ml:15,price:880},{ml:30,price:1690}], tags: [], inStock: true },
  { id: "armaf-cdni-iconic", name: "Armaf Club de Nuit Iconic", brand: "Armaf", sizes: [{ml:3,price:200},{ml:5,price:330},{ml:10,price:590},{ml:15,price:880}], tags: [], inStock: true },
  { id: "french-avenue-aether", name: "French Avenue Aether", brand: "French Avenue", sizes: [{ml:3,price:200},{ml:5,price:330},{ml:10,price:590},{ml:15,price:880},{ml:30,price:1690}], tags: [], inStock: true },
  { id: "french-avenue-liquid-brun", name: "French Avenue Liquid Brun", brand: "French Avenue", sizes: [{ml:3,price:200},{ml:5,price:330},{ml:10,price:590},{ml:15,price:880},{ml:30,price:1690}], tags: [], inStock: true },
  { id: "lalique-encre-noire-sport", name: "Lalique Encre Noire Sport", brand: "Lalique", sizes: [{ml:3,price:200},{ml:5,price:330},{ml:10,price:590},{ml:15,price:880},{ml:30,price:1690}], tags: [], inStock: true },
  { id: "rasasi-hawas-lava-gold", name: "Rasasi Hawas Lava Gold", brand: "Rasasi", sizes: [{ml:3,price:190},{ml:5,price:320},{ml:10,price:550},{ml:15,price:810},{ml:30,price:1570}], tags: [], inStock: true },
  { id: "rasasi-hawas-thunder", name: "Rasasi Hawas Thunder", brand: "Rasasi", sizes: [{ml:3,price:190},{ml:5,price:320},{ml:10,price:550},{ml:15,price:810},{ml:30,price:1570}], tags: [], inStock: true },
  { id: "french-avenue-vulcan-feu", name: "French Avenue Vulcan Feu", brand: "French Avenue", sizes: [{ml:3,price:200},{ml:5,price:340},{ml:10,price:620},{ml:15,price:910},{ml:30,price:1750}], tags: [], inStock: true },
  { id: "french-avenue-vulcan-sable", name: "French Avenue Vulcan Sable", brand: "French Avenue", sizes: [{ml:3,price:200},{ml:5,price:340},{ml:10,price:620},{ml:15,price:910},{ml:30,price:1750}], tags: [], inStock: true },
  { id: "french-avenue-atlantis", name: "French Avenue Atlantis", brand: "French Avenue", sizes: [{ml:3,price:200},{ml:5,price:340},{ml:10,price:620},{ml:15,price:910},{ml:30,price:1750}], tags: ["new"], inStock: true },
  { id: "afnan-supremacy-not-only-intense", name: "Afnan Supremacy Not Only Intense", brand: "Afnan", sizes: [{ml:3,price:220},{ml:5,price:350},{ml:10,price:650},{ml:15,price:950},{ml:30,price:1840}], tags: [], inStock: true },
  { id: "afnan-turathi-brown", name: "Afnan Turathi Brown", brand: "Afnan", sizes: [{ml:3,price:220},{ml:5,price:350},{ml:10,price:650},{ml:15,price:950},{ml:30,price:1840}], tags: [], inStock: true },
  { id: "french-avenue-magnetiq", name: "French Avenue X Aromatix Magnetiq", brand: "French Avenue", sizes: [{ml:3,price:220},{ml:5,price:350},{ml:10,price:650},{ml:15,price:950}], tags: ["new"], inStock: true },
  { id: "french-avenue-platine-blanc", name: "French Avenue X Aromatix Platine Blanc", brand: "French Avenue", sizes: [{ml:3,price:220},{ml:5,price:350},{ml:10,price:650},{ml:15,price:950}], tags: [], inStock: true },
  { id: "french-avenue-vulcan-black-friday", name: "French Avenue Vulcan Black Friday LE", brand: "French Avenue", sizes: [{ml:3,price:230},{ml:5,price:370},{ml:10,price:680},{ml:15,price:990}], tags: ["limited"], inStock: true },
  { id: "al-haramain-amber-oud-gold", name: "Al Haramain Amber Oud Gold Edition", brand: "Al Haramain", sizes: [{ml:3,price:240},{ml:5,price:390},{ml:10,price:740},{ml:15,price:1090}], tags: [], inStock: true },
  { id: "hugo-boss-bottled-infinite", name: "Hugo Boss Bottled Infinite", brand: "Hugo Boss", sizes: [{ml:3,price:240},{ml:5,price:390},{ml:10,price:740},{ml:15,price:1090}], tags: [], inStock: true },
  { id: "jpg-le-male", name: "JPG Le Male", brand: "Jean Paul Gaultier", sizes: [{ml:3,price:240},{ml:5,price:390},{ml:10,price:740},{ml:15,price:1090}], tags: ["restocked"], inStock: true },
  { id: "mercedes-club-black", name: "Mercedes Benz Club Black EDT", brand: "Mercedes Benz", sizes: [{ml:3,price:240},{ml:5,price:390},{ml:10,price:740},{ml:15,price:1090}], tags: [], inStock: true },
  { id: "missoni-wave", name: "Missoni Wave", brand: "Missoni", sizes: [{ml:3,price:240},{ml:5,price:390},{ml:10,price:740},{ml:15,price:1090}], tags: [], inStock: true },
  { id: "al-haramain-amber-oud-aqua-dubai", name: "Al Haramain Amber Oud Aqua Dubai", brand: "Al Haramain", sizes: [{ml:3,price:260},{ml:5,price:420},{ml:10,price:790},{ml:15,price:1170},{ml:30,price:2290}], tags: [], inStock: true },
  { id: "al-haramain-amber-oud-dubai-night", name: "Al Haramain Amber Oud Dubai Night", brand: "Al Haramain", sizes: [{ml:3,price:260},{ml:5,price:420},{ml:10,price:790},{ml:15,price:1170}], tags: [], inStock: true },
  { id: "al-haramain-amber-oud-999", name: "Al Haramain Amber Oud Gold 999.9 Dubai Edition", brand: "Al Haramain", sizes: [{ml:3,price:260},{ml:5,price:420},{ml:10,price:790},{ml:15,price:1170},{ml:30,price:2290}], tags: [], inStock: true },
  { id: "jpg-le-beau", name: "JPG Le Beau", brand: "Jean Paul Gaultier", sizes: [{ml:3,price:260},{ml:5,price:420},{ml:10,price:790},{ml:15,price:1170},{ml:30,price:2250}], tags: [], inStock: true },
  { id: "jpg-le-male-le-parfum", name: "JPG Le Male Le Parfum", brand: "Jean Paul Gaultier", sizes: [{ml:3,price:260},{ml:5,price:420},{ml:10,price:790},{ml:15,price:1170},{ml:30,price:2300}], tags: [], inStock: true },
  { id: "afnan-supremacy-collectors", name: "Afnan Supremacy Collector's Edition", brand: "Afnan", sizes: [{ml:3,price:280},{ml:5,price:450},{ml:10,price:850},{ml:15,price:1250}], tags: [], inStock: true },
  { id: "al-haramain-amber-oud-future", name: "Al Haramain Amber Oud Future Dubai", brand: "Al Haramain", sizes: [{ml:3,price:280},{ml:5,price:450},{ml:10,price:850},{ml:15,price:1250}], tags: ["new"], inStock: true },
  { id: "hugo-boss-bottled-bold-citrus", name: "Hugo Boss Bottled Bold Citrus", brand: "Hugo Boss", sizes: [{ml:3,price:300},{ml:5,price:490},{ml:10,price:950},{ml:15,price:1400},{ml:30,price:2760}], tags: [], inStock: true },
  { id: "mancera-instant-crush", name: "Mancera Instant Crush", brand: "Mancera", sizes: [{ml:3,price:300},{ml:5,price:490},{ml:10,price:950},{ml:15,price:1400},{ml:30,price:2760}], tags: [], inStock: true },
  { id: "missoni-parfum-homme", name: "Missoni Parfum Pour Homme", brand: "Missoni", sizes: [{ml:3,price:300},{ml:5,price:490},{ml:10,price:950},{ml:15,price:1400}], tags: [], inStock: true },
  { id: "jpg-le-beau-paradise-garden", name: "JPG Le Beau Paradise Garden", brand: "Jean Paul Gaultier", sizes: [{ml:3,price:320},{ml:5,price:530},{ml:10,price:990},{ml:15,price:1490},{ml:30,price:2940}], tags: [], inStock: true },
  { id: "azzaro-most-wanted-edp-intense", name: "Azzaro The Most Wanted EDP Intense", brand: "Azzaro", sizes: [{ml:3,price:350},{ml:5,price:570},{ml:10,price:1090},{ml:15,price:1580},{ml:30,price:3050}], tags: [], inStock: true },
  { id: "mancera-french-riviera", name: "Mancera French Riviera", brand: "Mancera", sizes: [{ml:3,price:350},{ml:5,price:570},{ml:10,price:1090},{ml:15,price:1580},{ml:30,price:3050}], tags: [], inStock: true },
  { id: "prada-luna-rossa-ocean-edp", name: "Prada Luna Rossa Ocean EDP", brand: "Prada", sizes: [{ml:3,price:350},{ml:5,price:570},{ml:10,price:1090},{ml:15,price:1580}], tags: [], inStock: true },
  { id: "armaf-cdni-extrait", name: "Club de Nuit Intense Man Extrait", brand: "Armaf", sizes: [{ml:3,price:370},{ml:5,price:590},{ml:10,price:1130},{ml:15,price:1650}], tags: [], inStock: true },
  { id: "azzaro-most-wanted-parfum", name: "Azzaro The Most Wanted Parfum", brand: "Azzaro", sizes: [{ml:3,price:370},{ml:5,price:590},{ml:10,price:1130},{ml:15,price:1650},{ml:30,price:3250}], tags: [], inStock: true },
  { id: "hugo-boss-bottled-absolu", name: "Hugo Boss Bottled Absolu", brand: "Hugo Boss", sizes: [{ml:3,price:390},{ml:5,price:630},{ml:10,price:1200},{ml:15,price:1790},{ml:30,price:3500}], tags: [], inStock: true },
  { id: "hugo-boss-bottled-elixir", name: "Hugo Boss Bottled Elixir", brand: "Hugo Boss", sizes: [{ml:3,price:390},{ml:5,price:630},{ml:10,price:1200},{ml:15,price:1790}], tags: [], inStock: true },
  { id: "bvlgari-man-in-black-edp", name: "Bvlgari Man In Black EDP", brand: "Bvlgari", sizes: [{ml:3,price:390},{ml:5,price:630},{ml:10,price:1200},{ml:15,price:1790}], tags: [], inStock: true },
  { id: "armani-stronger-absolutely", name: "Giorgio Armani Stronger With You Absolutely", brand: "Giorgio Armani", sizes: [{ml:3,price:410},{ml:5,price:670},{ml:10,price:1290},{ml:15,price:1900}], tags: [], inStock: true },
  { id: "armani-stronger-intensely", name: "Giorgio Armani Stronger With You Intensely", brand: "Giorgio Armani", sizes: [{ml:3,price:410},{ml:5,price:670},{ml:10,price:1290},{ml:15,price:1900}], tags: [], inStock: true },
  { id: "jpg-le-male-elixir", name: "JPG Le Male Elixir", brand: "Jean Paul Gaultier", sizes: [{ml:3,price:410},{ml:5,price:670},{ml:10,price:1290},{ml:15,price:1900}], tags: [], inStock: true },
  { id: "ysl-y-edp", name: "YSL Y EDP", brand: "Yves Saint Laurent", sizes: [{ml:3,price:420},{ml:5,price:690},{ml:10,price:1350},{ml:15,price:2030}], tags: [], inStock: true },
];

const exclusiveProducts = [
  { id: "bogart-silver-scent-pure", name: "Jacques Bogart Silver Scent Pure", brand: "Jacques Bogart", sizes: [{ml:3,price:220},{ml:5,price:350}], tags: ["discontinued"], inStock: true },
  { id: "dunhill-icon", name: "Alfred Dunhill Icon", brand: "Alfred Dunhill", sizes: [{ml:3,price:320},{ml:5,price:530}], tags: ["discontinued"], inStock: true },
  { id: "dg-light-blue-intense", name: "Light Blue Eau Intense", brand: "Dolce & Gabbana", sizes: [{ml:3,price:410},{ml:5,price:670}], tags: ["discontinued"], inStock: true },
  { id: "jpg-le-male-navy", name: "JPG Le Male In The Navy (2018)", brand: "Jean Paul Gaultier", sizes: [{ml:3,price:430},{ml:5,price:700}], tags: ["discontinued"], inStock: true },
  { id: "jpg-ultra-male-old", name: "JPG Ultra Male (Old Formulation)", brand: "Jean Paul Gaultier", sizes: [{ml:3,price:430},{ml:5,price:700}], tags: ["discontinued"], inStock: true },
  { id: "armani-adg-profondo-2020", name: "Giorgio Armani ADG Profondo 2020", brand: "Giorgio Armani", sizes: [{ml:3,price:430},{ml:5,price:700}], tags: ["discontinued"], inStock: true },
  { id: "armani-adg-absolu", name: "Giorgio Armani ADG Absolu", brand: "Giorgio Armani", sizes: [{ml:3,price:540},{ml:5,price:880}], tags: ["discontinued"], inStock: true },
  { id: "dior-homme-sport-2017", name: "Dior Homme Sport 2017", brand: "Dior", sizes: [{ml:3,price:600},{ml:5,price:950}], tags: ["discontinued"], inStock: true },
  { id: "dior-homme-intense", name: "Dior Homme Intense", brand: "Dior", sizes: [{ml:3,price:600},{ml:5,price:980}], tags: ["discontinued"], inStock: true },
  { id: "gucci-guilty-elixir", name: "Gucci Guilty Elixir", brand: "Gucci", sizes: [{ml:3,price:950},{ml:5,price:1550}], tags: ["discontinued"], inStock: true },
  { id: "amouage-enclave", name: "Amouage Enclave", brand: "Amouage", sizes: [{ml:3,price:1200},{ml:5,price:1950}], tags: [], inStock: true },
];

const specialItems = [
  { id: "ysl-tuxedo-sample", name: "YSL Tuxedo 2ml Official Sample", brand: "Yves Saint Laurent", sizes: [{ml:2,price:650}], tags: ["exclusive"], inStock: true, isSpecial: true },
];

const allBrands = [...new Set([...regularProducts, ...exclusiveProducts].map(p => p.brand))].sort();

const bestsellers = [
  "rasasi-hawas-ice","jpg-le-male","afnan-9pm","armaf-cdni-edp",
  "jpg-le-beau","rasasi-hawas","azzaro-most-wanted-edp-intense","hugo-boss-bottled-absolu"
];

const productDetails = {
  "afnan-9pm": { top: ["Apple","Pineapple","Bergamot"], heart: ["Cinnamon","Lavender","Rose"], base: ["Vanilla","Amber","Musk","Patchouli"], accords: ["Sweet","Spicy","Fruity","Woody"], family: "Oriental / Spicy" },
  "afnan-modest-une": { top: ["Bergamot","Lemon","Mandarin"], heart: ["Jasmine","Rose","Iris"], base: ["Cedarwood","Musk","Amber"], accords: ["Fresh","Floral","Citrus","Woody"], family: "Floral" },
  "afnan-supremacy-collectors": { top: ["Bergamot","Cardamom","Nutmeg"], heart: ["Jasmine","Rose","Leather"], base: ["Oud","Amber","Sandalwood","Musk"], accords: ["Oriental","Spicy","Woody","Oud"], family: "Oriental / Spicy" },
  "afnan-supremacy-not-only-intense": { top: ["Bergamot","Lemon","Pineapple"], heart: ["Apple","Jasmine","Cinnamon"], base: ["Vanilla","Amber","Musk","Sandalwood"], accords: ["Sweet","Spicy","Fresh","Woody"], family: "Oriental / Spicy" },
  "afnan-turathi-brown": { top: ["Saffron","Rose","Oud"], heart: ["Agarwood","Amber","Patchouli"], base: ["Sandalwood","Musk","Benzoin"], accords: ["Oriental","Woody","Resinous","Oud"], family: "Oriental / Spicy" },
  "al-haramain-amber-oud-aqua-dubai": { top: ["Sea Notes","Bergamot","Mandarin"], heart: ["Aquatic Notes","Jasmine","Violet"], base: ["Amber","Musk","Woody Notes"], accords: ["Aquatic","Fresh","Oriental","Marine"], family: "Aquatic / Fresh" },
  "al-haramain-amber-oud-dubai-night": { top: ["Bergamot","Saffron","Pink Pepper"], heart: ["Oud","Rose","Labdanum"], base: ["Amber","Sandalwood","Musk","Vanilla"], accords: ["Oriental","Oud","Spicy","Resinous"], family: "Oriental / Spicy" },
  "al-haramain-amber-oud-future": { top: ["Bergamot","Lemon","Pink Pepper"], heart: ["Violet","Iris","Rose"], base: ["Amber","Musk","Sandalwood","Oud"], accords: ["Oriental","Fresh","Floral","Woody"], family: "Oriental / Spicy" },
  "al-haramain-amber-oud-999": { top: ["Bergamot","Saffron","Cardamom"], heart: ["Rose","Oud","Patchouli"], base: ["Amber","Sandalwood","Musk","Vanilla","Honey"], accords: ["Oriental","Oud","Sweet","Spicy"], family: "Oriental / Spicy" },
  "al-haramain-amber-oud-gold": { top: ["Bergamot","Pink Pepper","Saffron"], heart: ["Rose","Oud","Patchouli"], base: ["Amber","Sandalwood","Musk","Vanilla"], accords: ["Oriental","Oud","Spicy","Sweet"], family: "Oriental / Spicy" },
  "dunhill-icon": { top: ["Grapefruit","Bergamot","Cardamom"], heart: ["Rose","Oud","Violet"], base: ["Sandalwood","Amber","Musk","Vetiver"], accords: ["Spicy","Woody","Floral","Fresh"], family: "Woody" },
  "amouage-enclave": { top: ["Lemon","Bergamot","Cardamom"], heart: ["Iris","Violet","Rose"], base: ["Cedarwood","Sandalwood","Musk","Amber"], accords: ["Powdery","Floral","Woody","Fresh"], family: "Floral" },
  "armaf-cdni-iconic": { top: ["Blackcurrant","Bergamot","Apple"], heart: ["Jasmine","Rose","Iris"], base: ["Sandalwood","Musk","Amber","Cedarwood"], accords: ["Fresh","Floral","Woody","Aromatic"], family: "Woody" },
  "armaf-cdni-edp": { top: ["Lemon","Pineapple","Blackcurrant","Bergamot"], heart: ["Rose","Jasmine","Birch"], base: ["Musk","Ambergris","Vetiver","Patchouli"], accords: ["Woody","Citrus","Fresh","Smoky"], family: "Woody" },
  "armaf-cdni-extrait": { top: ["Lemon","Pineapple","Blackcurrant","Bergamot"], heart: ["Rose","Jasmine","Birch"], base: ["Musk","Ambergris","Vetiver","Patchouli"], accords: ["Woody","Citrus","Smoky","Intense"], family: "Woody" },
  "armaf-cdni-milestone": { top: ["Lemon","Bergamot","Apple","Pink Pepper"], heart: ["Geranium","Jasmine","Violet"], base: ["Vetiver","Musk","Ambergris","Sandalwood"], accords: ["Woody","Citrus","Fresh","Aromatic"], family: "Woody" },
  "azzaro-most-wanted-edp-intense": { top: ["Cardamom","Lavender","Grapefruit"], heart: ["Labdanum","Tobacco"], base: ["Vanilla","Amber","Musk"], accords: ["Spicy","Oriental","Sweet","Aromatic"], family: "Oriental / Spicy" },
  "azzaro-most-wanted-parfum": { top: ["Cardamom","Grapefruit"], heart: ["Tobacco","Labdanum"], base: ["Vanilla","Amber","Musk","Tonka Bean"], accords: ["Spicy","Oriental","Sweet","Tobacco"], family: "Oriental / Spicy" },
  "bentley-silverlake": { top: ["Bergamot","Lemon","Grapefruit"], heart: ["Lavender","Geranium","Violet"], base: ["Vetiver","Sandalwood","Cedar","Musk"], accords: ["Fresh","Aromatic","Woody","Citrus"], family: "Aromatic" },
  "bvlgari-man-in-black-edp": { top: ["Cardamom","Iris","Black Pepper"], heart: ["Rum","Guaiac Wood","Tobacco"], base: ["Benzoin","Sandalwood","Amber"], accords: ["Spicy","Woody","Oriental","Leather"], family: "Oriental / Spicy" },
  "davidoff-cool-water": { top: ["Mint","Lavender","Coriander","Rosemary"], heart: ["Geranium","Neroli","Jasmine","Sandalwood"], base: ["Musk","Oakmoss","Tobacco","Amber","Cedar"], accords: ["Aquatic","Fresh","Aromatic","Woody"], family: "Aquatic / Fresh" },
  "davidoff-indigo": { top: ["Sea Notes","Bergamot","Pineapple"], heart: ["Muguet","Sandalwood"], base: ["Musk","Amber","Oakmoss"], accords: ["Aquatic","Fresh","Fruity"], family: "Aquatic / Fresh" },
  "dior-homme-intense": { top: ["Iris","Lavender","Bergamot"], heart: ["Ambrette","Pear","Vetiver"], base: ["Woody Notes","Musk","Virginia Cedar"], accords: ["Powdery","Floral","Woody","Sweet"], family: "Floral" },
  "dior-homme-sport-2017": { top: ["Grapefruit","Bergamot","Pepper"], heart: ["Iris","Vetiver","Cardamom"], base: ["Woody Notes","Musk","Ambroxan"], accords: ["Fresh","Citrus","Aromatic","Woody"], family: "Citrus" },
  "french-avenue-aether": { top: ["Bergamot","Cardamom","Pink Pepper"], heart: ["Lavender","Geranium","Iris"], base: ["Sandalwood","Vetiver","Musk"], accords: ["Aromatic","Woody","Fresh","Spicy"], family: "Aromatic" },
  "french-avenue-atlantis": { top: ["Sea Notes","Bergamot","Mandarin"], heart: ["Jasmine","Violet","Marine"], base: ["Musk","Sandalwood","Amber"], accords: ["Aquatic","Fresh","Marine","Woody"], family: "Aquatic / Fresh" },
  "french-avenue-liquid-brun": { top: ["Bergamot","Mandarin","Cardamom"], heart: ["Cinnamon","Bourbon","Leather"], base: ["Tobacco","Oud","Sandalwood","Amber"], accords: ["Oriental","Spicy","Woody","Leather"], family: "Oriental / Spicy" },
  "french-avenue-vulcan-black-friday": { top: ["Black Pepper","Bergamot","Cardamom"], heart: ["Leather","Patchouli","Labdanum"], base: ["Oud","Amber","Sandalwood","Musk"], accords: ["Spicy","Leather","Oriental","Dark"], family: "Oriental / Spicy" },
  "french-avenue-vulcan-feu": { top: ["Bergamot","Pink Pepper","Cardamom"], heart: ["Cinnamon","Leather","Patchouli"], base: ["Oud","Amber","Sandalwood","Musk"], accords: ["Spicy","Oriental","Woody","Leather"], family: "Oriental / Spicy" },
  "french-avenue-vulcan-sable": { top: ["Bergamot","Grapefruit","Lemon"], heart: ["Lavender","Geranium","Violet"], base: ["Sandalwood","Vetiver","Cedar","Musk"], accords: ["Fresh","Aromatic","Woody","Citrus"], family: "Aromatic" },
  "french-avenue-magnetiq": { top: ["Bergamot","Pepper","Cardamom"], heart: ["Geranium","Iris","Lavender"], base: ["Vetiver","Cedar","Musk","Amber"], accords: ["Aromatic","Fresh","Woody","Spicy"], family: "Aromatic" },
  "french-avenue-platine-blanc": { top: ["Bergamot","Mandarin","Lemon"], heart: ["Jasmine","Violet","Rose"], base: ["Musk","Sandalwood","Cedar"], accords: ["Fresh","Floral","Citrus","Woody"], family: "Floral" },
  "armani-adg-absolu": { top: ["Lemon","Bergamot","Petitgrain"], heart: ["Orange Blossom","Cardamom","Rosemary"], base: ["Tonka Bean","Ambroxan","Sandalwood"], accords: ["Fresh","Citrus","Woody","Aromatic"], family: "Citrus" },
  "armani-adg-profondo-2020": { top: ["Bergamot","Lemon","Mandarin"], heart: ["Aquatic Notes","Rosemary","Apple"], base: ["Ambroxan","Musk","Woody Notes"], accords: ["Aquatic","Fresh","Woody","Marine"], family: "Aquatic / Fresh" },
  "armani-stronger-absolutely": { top: ["Vanilla","Lavender","Bergamot"], heart: ["Chestnut","Iris","Cinnamon"], base: ["Musk","Amber","Sandalwood","Clearwood"], accords: ["Gourmand","Sweet","Aromatic","Woody"], family: "Gourmand" },
  "armani-stronger-intensely": { top: ["Cardamom","Lavender","Pink Pepper"], heart: ["Chestnut","Cashmeran","Iris"], base: ["Vanilla","Musk","Amber","Sandalwood"], accords: ["Spicy","Woody","Sweet","Aromatic"], family: "Oriental / Spicy" },
  "gucci-guilty-elixir": { top: ["Incense","Cardamom","Pink Pepper"], heart: ["Leather","Violet","Patchouli"], base: ["Amber","Sandalwood","Musk","Oud"], accords: ["Oriental","Spicy","Leather","Woody"], family: "Oriental / Spicy" },
  "gulf-orchid-naseem": { top: ["Grapefruit","Green Pear","Basil","Rhubarb"], heart: ["Freesia","Amberwood","Rose","Marine Accord"], base: ["Moss","Caramel","Amber","Musk"], accords: ["Fresh","Fruity","Aquatic","Gourmand"], family: "Aquatic / Fresh" },
  "hugo-boss-bottled-absolu": { top: ["Apple","Bergamot","Ginger"], heart: ["Geranium","Rose","Jasmine"], base: ["Sandalwood","Vetiver","Musk","Amber"], accords: ["Spicy","Woody","Fresh","Aromatic"], family: "Woody" },
  "hugo-boss-bottled-bold-citrus": { top: ["Grapefruit","Lemon","Bergamot"], heart: ["Geranium","Sage","Ginger"], base: ["Vetiver","Cedar","Musk"], accords: ["Citrus","Fresh","Aromatic","Woody"], family: "Citrus" },
  "hugo-boss-bottled-elixir": { top: ["Ginger","Pink Pepper","Bergamot"], heart: ["Patchouli","Geranium","Jasmine"], base: ["Vetiver","Musk","Sandalwood"], accords: ["Spicy","Aromatic","Woody","Fresh"], family: "Woody" },
  "hugo-boss-bottled-infinite": { top: ["Apple","Bergamot","Plum"], heart: ["Cinnamon","Mahogany","Geranium"], base: ["Sandalwood","Vanilla","Amber","Cedar"], accords: ["Spicy","Woody","Fruity","Aromatic"], family: "Woody" },
  "bogart-silver-scent-pure": { top: ["Bergamot","Lavender","Lemon"], heart: ["Iris","Violet","Geranium"], base: ["Sandalwood","Cedar","Musk","Amber"], accords: ["Fresh","Aromatic","Woody","Citrus"], family: "Aromatic" },
  "jpg-le-beau": { top: ["Coconut","Bergamot","Lemon"], heart: ["Vanilla Bourbon","Iris","Orange Blossom"], base: ["Woody Notes","White Musks"], accords: ["Gourmand","Fresh","Sweet","Aquatic"], family: "Gourmand" },
  "jpg-le-beau-paradise-garden": { top: ["Bergamot","Coconut","Mango"], heart: ["Iris","Orange Blossom","Jasmine"], base: ["Vanilla","Musk","Sandalwood"], accords: ["Tropical","Fruity","Floral","Sweet"], family: "Gourmand" },
  "jpg-le-male": { top: ["Lavender","Mint","Bergamot"], heart: ["Cumin","Cinnamon","Orange Blossom"], base: ["Musk","Amber","Sandalwood","Vanilla"], accords: ["Aromatic","Spicy","Oriental","Sweet"], family: "Oriental / Spicy" },
  "jpg-le-male-elixir": { top: ["Cardamom","Honey","Lavender"], heart: ["Iris","Orange Blossom"], base: ["Vanilla","Amber","Tonka Bean","Musk"], accords: ["Oriental","Sweet","Aromatic","Honey"], family: "Oriental / Spicy" },
  "jpg-le-male-navy": { top: ["Bergamot","Lemon","Sea Notes"], heart: ["Lavender","Iris","Geranium"], base: ["Musk","Amber","Cedar","Oakmoss"], accords: ["Aquatic","Aromatic","Fresh","Woody"], family: "Aquatic / Fresh" },
  "jpg-le-male-le-parfum": { top: ["Bergamot","Cardamom","Lavender"], heart: ["Iris","Orange Blossom"], base: ["Vanilla","Leather","Amber"], accords: ["Oriental","Aromatic","Sweet","Leather"], family: "Oriental / Spicy" },
  "jpg-ultra-male-old": { top: ["Pear","Lavender","Mint"], heart: ["Cinnamon","Orange Blossom"], base: ["Vanilla","Amber","Sandalwood"], accords: ["Sweet","Spicy","Fruity","Oriental"], family: "Oriental / Spicy" },
  "lalique-encre-noire-sport": { top: ["Grapefruit","Cypress"], heart: ["Vetiver"], base: ["Woody Notes","Musk"], accords: ["Fresh","Woody","Citrus","Aromatic"], family: "Woody" },
  "lattafa-angham": { top: ["Ginger","Mandarin","Pink Pepper"], heart: ["Lavender","Praline","Cacao","Jasmine"], base: ["Vanilla","Amber","Musk"], accords: ["Gourmand","Sweet","Vanilla","Floral"], family: "Gourmand" },
  "lattafa-dynasty": { top: ["Bergamot","Ginger","Clary Sage","Raspberry","Nutmeg"], heart: ["Rooibos Tea","Suede"], base: ["Cedarwood","Cashmeran","Amberwood"], accords: ["Spicy","Woody","Tea","Fresh"], family: "Woody" },
  "lattafa-khamrah-qahwa": { top: ["Cinnamon","Cardamom","Ginger"], heart: ["Praline","Candied Fruits","White Flowers"], base: ["Vanilla","Coffee","Tonka Bean","Benzoin","Musk"], accords: ["Oriental","Gourmand","Spicy","Sweet"], family: "Gourmand" },
  "lattafa-maahir-legacy": { top: ["Lime","Mint","Grapefruit","Lavender","Pineapple"], heart: ["Black Pepper","Rosemary","Juniper Berry","Geranium","Frankincense"], base: ["Ambroxan","Vetiver","Oakmoss","Cashmeran","Tonka Bean"], accords: ["Fresh","Aromatic","Woody","Citrus"], family: "Aquatic / Fresh" },
  "lattafa-teriaq-intense": { top: ["Bergamot","Saffron"], heart: ["Plum Liquor","Cinnamon"], base: ["Tonka Bean","Amber","Benzoin"], accords: ["Oriental","Spicy","Boozy","Sweet"], family: "Oriental / Spicy" },
  "dg-light-blue-intense": { top: ["Lemon","Apple","Grapefruit"], heart: ["Jasmine","Rose","Bamboo"], base: ["Musk","Amber","Sandalwood"], accords: ["Fresh","Floral","Citrus","Aquatic"], family: "Aquatic / Fresh" },
  "mancera-french-riviera": { top: ["Lemon","Bergamot","Lime"], heart: ["Jasmine","Rose","Galbanum"], base: ["Musk","Ambergris","Cedar"], accords: ["Fresh","Citrus","Floral","Marine"], family: "Aquatic / Fresh" },
  "mancera-instant-crush": { top: ["Bergamot","Black Pepper","Cardamom"], heart: ["Violet","Iris","Leather"], base: ["Sandalwood","Amber","Musk","Tonka Bean"], accords: ["Spicy","Woody","Leather","Fresh"], family: "Woody" },
  "mercedes-club-black": { top: ["Lemon","Bergamot","Pepper"], heart: ["Labdanum","Oakmoss","Cyclamen"], base: ["Vetiver","Musk","Amber","Cedar"], accords: ["Aromatic","Woody","Fresh","Dark"], family: "Aromatic" },
  "missoni-parfum-homme": { top: ["Bergamot","Lemon","Orange"], heart: ["Jasmine","Lavender","Sage"], base: ["Sandalwood","Musk","Amber","Oakmoss"], accords: ["Aromatic","Fresh","Woody","Floral"], family: "Aromatic" },
  "missoni-wave": { top: ["Grapefruit","Bergamot","Lemon"], heart: ["Geranium","Sage","Lavender"], base: ["Musk","Cedarwood","Oakmoss"], accords: ["Fresh","Aromatic","Citrus","Woody"], family: "Aromatic" },
  "nautica-voyage": { top: ["Green Leaves","Apple"], heart: ["Lotus","Mimosa"], base: ["Musk","Cedar","Oakmoss","Amber"], accords: ["Aquatic","Fresh","Woody","Green"], family: "Aquatic / Fresh" },
  "prada-luna-rossa-ocean-edp": { top: ["Bergamot","Aldehydes","Marine"], heart: ["Iris","Rosewood","Vetiver"], base: ["Ambroxan","Sandalwood","Musk"], accords: ["Aquatic","Woody","Fresh","Marine"], family: "Aquatic / Fresh" },
  "rasasi-hawas": { top: ["Apple","Bergamot","Lemon","Cinnamon"], heart: ["Watery Notes","Plum","Orange Blossom","Cardamom"], base: ["Ambergris","Musk","Patchouli","Driftwood"], accords: ["Aquatic","Fresh","Fruity","Sweet"], family: "Aquatic / Fresh" },
  "rasasi-hawas-black": { top: ["Bergamot","Pineapple","Grapefruit"], heart: ["Patchouli","Cedarwood","Jasmine"], base: ["Oakmoss","Woody Notes","Amber"], accords: ["Fresh","Chypre","Woody","Citrus"], family: "Woody" },
  "rasasi-hawas-elixir": { top: ["Mint","Bergamot","Artemisia"], heart: ["Dark Chocolate","Lavender","Benzoin"], base: ["Vanilla","Tonka Bean","White Musk"], accords: ["Gourmand","Sweet","Minty","Oriental"], family: "Gourmand" },
  "rasasi-hawas-ice": { top: ["Apple","Italian Lemon","Sicilian Bergamot","Star Anise"], heart: ["Plum","Orange Blossom","Cardamom"], base: ["Musk","Amber","Driftwood","Moss"], accords: ["Fresh","Fruity","Sweet","Aquatic"], family: "Aquatic / Fresh" },
  "rasasi-hawas-kobra": { top: ["Ginger","Bergamot","Tangerine"], heart: ["Cinnamon","Green Tea","Neroli"], base: ["Musk","Woodsy Notes","Amber"], accords: ["Fresh","Aromatic","Tea","Citrus"], family: "Aquatic / Fresh" },
  "rasasi-hawas-lava-gold": { top: ["Pineapple","Grapefruit","Apple","Lemon"], heart: ["Leather","Oud","Saffron","Raspberry"], base: ["Patchouli","Amber","Moss","Caramel"], accords: ["Oriental","Fruity","Leather","Sweet"], family: "Oriental / Spicy" },
  "rasasi-hawas-malibu": { top: ["Pineapple","Orange","Grapefruit"], heart: ["Amber","Orris","Lavender"], base: ["Tonka Bean","Musk","Cashmeran","Patchouli"], accords: ["Tropical","Fruity","Floral","Sweet"], family: "Aquatic / Fresh" },
  "rasasi-hawas-thunder": { top: ["Bergamot","Ginger","Apple"], heart: ["Spicy Notes"], base: ["Woody Notes","Amber"], accords: ["Fresh","Spicy","Woody","Aromatic"], family: "Aromatic" },
  "rasasi-hawas-tropical": { top: ["Coconut Water","Fig Leaf","Ginger"], heart: ["Coconut","Fig","Mint"], base: ["Sandalwood","Tonka Bean","Musk"], accords: ["Tropical","Coconut","Green","Fresh"], family: "Aquatic / Fresh" },
  "rasasi-shuhrah-elixir": { top: ["Lemon","Ginger","Mandarin"], heart: ["Violet","Rose","Amber"], base: ["Ambroxan","Sandalwood","Patchouli","Oud"], accords: ["Spicy","Woody","Citrus","Aromatic"], family: "Woody" },
  "rayhaan-aquatica": { top: ["Lime","Coconut Milk","Bergamot","Mandarin"], heart: ["Sugar Cane","Jasmine","Hibiscus","Gardenia"], base: ["Rum","Musk","Tonka Bean","Patchouli"], accords: ["Aquatic","Tropical","Citrus","Gourmand"], family: "Aquatic / Fresh" },
  "rayhaan-lion": { top: ["Lavender","Pear","Mint","Bergamot"], heart: ["Cinnamon","Clary Sage","Cumin"], base: ["Vanilla","Amber","Cedar","Patchouli"], accords: ["Spicy","Sweet","Aromatic","Woody"], family: "Oriental / Spicy" },
  "rayhaan-terra": { top: ["Cardamom","Elemi","Lemon","Bergamot","Sichuan Pepper"], heart: ["Patchouli","Coriander","Cumin","Anise","Saffron","Orange Blossom","Rose","Geranium"], base: ["Frankincense","Amber","Vanilla","Benzoin","Oud","Musk","Labdanum","Ambergris"], accords: ["Spicy","Oriental","Woody","Resinous"], family: "Oriental / Spicy" },
  "riiffs-fareed": { top: ["Cardamom","Pepper"], heart: ["Bergamot","Lavender","Geranium"], base: ["Cedarwood","Vetiver","Tonka Bean"], accords: ["Aromatic","Spicy","Woody","Fresh"], family: "Aromatic" },
  "ysl-y-edp": { top: ["Bergamot","Ginger","Sage"], heart: ["Geranium","Cedar"], base: ["Tonka Bean","Musk","Amber"], accords: ["Woody","Fresh","Aromatic","Spicy"], family: "Woody" }
};

function buildDetailsPanel(id) {
  const d = productDetails[id];
  if (!d) return '';
  const pills = d.accords.map(a => `<span class="accord-pill">${a}</span>`).join('');
  return `<button class="details-toggle" onclick="toggleDetails('${id}')">&#9660; Fragrance Notes</button><div class="card-details" id="details-${id}"><div class="notes-section"><div class="notes-label">Top</div><div class="notes-text">${d.top.join(', ')}</div></div><div class="notes-section"><div class="notes-label">Heart</div><div class="notes-text">${d.heart.join(', ')}</div></div><div class="notes-section"><div class="notes-label">Base</div><div class="notes-text">${d.base.join(', ')}</div></div><div class="accords-row">${pills}</div><div class="family-text">${d.family}</div></div>`;
}

function toggleDetails(id) {
  const panel = document.getElementById('details-' + id);
  const btn = panel.previousElementSibling;
  panel.classList.toggle('open');
  btn.innerHTML = panel.classList.contains('open') ? '&#9650; Hide Notes' : '&#9660; Fragrance Notes';
}
